default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  database: simplerqms_production
  username: backend
  password: <%= ENV["APP_FEEDSTRAP_COM_DATABASE_PASSWORD"] %>