name: 'simplerqms-test'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=PPk4nz5Zd1csikqjqnsc
      - POSTGRES_USER=backend
      - POSTGRES_DB=simplerqms_test_db
    volumes:
      - './init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql'
      # Uncomment the following line to enable data persistence between container restarts
      # - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U backend -d simplerqms_test_db']
      interval: 3s
      timeout: 3s
      retries: 5

  node:
    image: node:20.11.1-alpine
    restart: 'always'
    ports:
      - '3000:3000'
    volumes:
      - './node:/app'
      - /app/node_modules
    working_dir: /app
    command: npm run live
    environment:
      - DATABASE_PASSWORD=PPk4nz5Zd1csikqjqnsc
    depends_on:
      postgres:
        condition: 'service_healthy'

  # rails:
  #   image: "simplerqms-test/rails_api:latest"
  #   build:
  #     context: "./rails_api"
  #     dockerfile: "Dockerfile"
  #   restart: "always"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./rails_api:/usr/src/app"
  #   environment:
  #     - DATABASE_URL=postgresql://backend:PPk4nz5Zd1csikqjqnsc@postgres/simplerqms_test_db
  #     - RAILS_LOG_LEVEL=debug
  #   depends_on:
  #     postgres:
  #       condition: "service_healthy"

  # golang:
  #   image: "simplerqms-test/golang:latest"
  #   build:
  #     context: "./golang"
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./golang:/app
  #   environment:
  #     - DATABASE_URL=postgresql://backend:PPk4nz5Zd1csikqjqnsc@postgres/simplerqms_test_db
  #   depends_on:
  #     postgres:
  #       condition: "service_healthy"

  frontend:
    image: node:20.11.1-alpine
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - HOST=0.0.0.0
      - PORT=5173
# Uncomment this section to enable data persistence
# volumes:
#   postgres_data:
